repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # 使用最新版本的 isort
    hooks:
      - id: isort
        args: ["--profile", "black"]  # 可选: 与 Black 配合使用，保持一致的风格

  - repo: https://github.com/psf/black
    rev: 24.4.0  # 使用最新版本的 Black
    hooks:
      - id: black
        language_version: python3  # 确保使用 Python 3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - '--max-line-length=120'
          - '--extend-ignore=E203,E266,E501'  # Changed to extend-ignore and added E203