repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]  # Optional: harmonize style with Black
  - repo: https://github.com/psf/black
    rev: 24.4.0  # Use the latest version of Black
    hooks:
      - id: black
        language_version: python3  # Ensure you're using Python 3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args: ['--max-line-length=120']